data:
  root: /mnt/lustrenew/reid/SIXray/data
  train_list: /mnt/lustrenew/reid/SIXray/data/ImageSet/10/train.csv
  test_list: /mnt/lustrenew/reid/SIXray/data/ImageSet/10/test.csv
  train_img_size: 256
  test_img_size: 224
  batch_size: 16
  workers: 2
model:
  arch: resnet101
  num_classes: 5
  pretrained: ''
train:
  total_iter: 20000
  lr: 0.01
  lr_iters: [10000]
  lr_gamma: 0.1
  momentum: 0.9
  weight_decay: 0.0001
save_path: checkpoints/10/res101_b128_iter20000
save_freq: 1000
print_freq: 10
resume: False
